# Generated by Django 5.0.1 on 2024-11-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmakFeatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edmakFeatures.maincourse'),
        ),
    ]
