# Generated by Django 5.0.1 on 2024-11-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edmakFeatures', '0003_rename_name_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='courses',
        ),
    ]
