# Generated by Django 5.1.4 on 2024-12-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmakFeatures', '0008_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequest',
            name='course',
        ),
        migrations.AddField(
            model_name='courserequest',
            name='main_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edmakFeatures.maincourse'),
        ),
    ]
