# Generated by Django 5.1.4 on 2025-01-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmakFeatures', '0009_remove_courserequest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
